// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-gArBrSYcqKcF4mXmBFfGQyip3g_w4fQ',
    appId: '1:299582198723:web:ef1174a5dd5dd82d5a2376',
    messagingSenderId: '299582198723',
    projectId: 'animesee-31389',
    authDomain: 'animesee-31389.firebaseapp.com',
    storageBucket: 'animesee-31389.appspot.com',
    measurementId: 'G-7DYXPWDNM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLsUo5yQ-FYAJYpDYLP2QaC6xE8NyIomA',
    appId: '1:299582198723:android:3d5628eddc9323d85a2376',
    messagingSenderId: '299582198723',
    projectId: 'animesee-31389',
    storageBucket: 'animesee-31389.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjMvw-P3TKPFQlDcQU07xD2uwPbPWIssk',
    appId: '1:299582198723:ios:93ab0963115673435a2376',
    messagingSenderId: '299582198723',
    projectId: 'animesee-31389',
    storageBucket: 'animesee-31389.appspot.com',
    iosClientId: '299582198723-vb0tec7g8car68d9qn7e3ttbfur08boj.apps.googleusercontent.com',
    iosBundleId: 'com.example.animesee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjMvw-P3TKPFQlDcQU07xD2uwPbPWIssk',
    appId: '1:299582198723:ios:93ab0963115673435a2376',
    messagingSenderId: '299582198723',
    projectId: 'animesee-31389',
    storageBucket: 'animesee-31389.appspot.com',
    iosClientId: '299582198723-vb0tec7g8car68d9qn7e3ttbfur08boj.apps.googleusercontent.com',
    iosBundleId: 'com.example.animesee',
  );
}
